#!/bin/bash

# Generate Docker environment file from pyproject.toml
# This script creates .env.docker with dynamic variables for Docker Compose

# Source utility functions
SOURCE_DIR="$(dirname "$0")"
source "$SOURCE_DIR/_utils.sh"

set -e  # Exit on any error

# Get project name from pyproject.toml
PROJECT_NAME=$(get_project_name)
if [ $? -ne 0 ]; then
    echo "❌ Failed to get project name from pyproject.toml"
    exit 1
fi

# Validate project name
validate_project_name "$PROJECT_NAME"
if [ $? -ne 0 ]; then
    exit 1
fi

# Generate .env.docker file
ENV_FILE="$SOURCE_DIR/.env.docker"

echo "📋 Generating Docker environment file with project name: $PROJECT_NAME"

cat > "$ENV_FILE" << EOF
# Docker Compose Environment Variables
# This file is automatically generated by the Docker scripts
# DO NOT EDIT MANUALLY - it will be overwritten

# Project name extracted from pyproject.toml
PROJECT_NAME=$PROJECT_NAME

# Set Docker Compose project name for consistent resource naming
COMPOSE_PROJECT_NAME=$PROJECT_NAME
EOF

echo "✅ Generated $ENV_FILE"
echo "📄 Contents:"
cat "$ENV_FILE"
