services:
  fastapi-test:
    build:
      context: ..
      dockerfile: scripts/compose/Dockerfile.test
    container_name: fastapi-test
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ../backend:/app/backend
      - ../tests:/app/tests
      - ../pytest.ini:/app/pytest.ini
    command: ["uv", "run", "pytest", "-v", "--tb=short"]
    profiles:
      - test

networks:
  default:
    name: fastapi-network
