version: '3.8'

services:
  fastapi-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: fastapi-app-prod
    ports:
      - "80:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env
    volumes:
      - fastapi-downloads:/app/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  fastapi-downloads:
    driver: local

networks:
  default:
    name: fastapi-network
