services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: ${PROJECT_NAME:-genai-agent}-app-prod
    ports:
      - "${HOST_PORT:-80}:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # env_file removed - passed via --env-file parameter to docker compose
    volumes:
      - downloads:/app/downloads
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  downloads:
    driver: local

networks:
  default:
    name: ${PROJECT_NAME:-genai-agent}-network
