services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: ${PROJECT_NAME:-genai-agent}-app
    ports:
      - "${HOST_PORT:-8000}:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    # env_file removed - passed via --env-file parameter to docker compose
    volumes:
      - ../downloads:/app/downloads
      - ../src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: ${PROJECT_NAME:-genai-agent}-network
