name: Release & Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false
        default: 'v1.0.0'
        type: string

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Release process
      run: |
        VERSION="${{ github.event.inputs.version || 'v1.0.0' }}"
        echo "🚀 Starting release process"
        echo "📋 Version: $VERSION"
        echo "✅ Release completed successfully"
